// <auto-generated />
using System;
using CoverAll_API.C_DAL.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoverAll_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220521012919_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("CoverAll_API.C_DAL.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CEP")
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Genero")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("UF")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CEP = "05668545",
                            CPF = "447.649.596-66",
                            Cidade = "São Paulo",
                            DataNascimento = new DateTime(1978, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Rua Pio XII",
                            Genero = "Masculino",
                            Nome = "Eduardo",
                            Sobrenome = "Noah Ramos",
                            Telefone = "88 3889-3701",
                            UF = "CE",
                            email = "eduardo_noah_ramos@trimempresas.com.br"
                        });
                });

            modelBuilder.Entity("CoverAll_API.C_DAL.Model.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdCLiente")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<string>("Usuario")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdCLiente = 1,
                            Senha = "admin",
                            Usuario = "admin"
                        });
                });

            modelBuilder.Entity("CoverAll_API.C_DAL.Model.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Frete")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdProdutoCliente")
                        .HasColumnType("int");

                    b.Property<string>("StatusEntrega")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusPagamento")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusPedido")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalAPagar")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("CoverAll_API.C_DAL.Model.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Tamanho")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cor = "Vermelho",
                            Descricao = "Tecido Vermelho",
                            Observacao = "",
                            Preco = 45.00m,
                            Quantidade = 10,
                            Tamanho = "XG"
                        },
                        new
                        {
                            Id = 2,
                            Cor = "Azul",
                            Descricao = "Tecido Azul Escuro",
                            Observacao = "",
                            Preco = 55.00m,
                            Quantidade = 20,
                            Tamanho = "GG"
                        },
                        new
                        {
                            Id = 3,
                            Cor = "Preto",
                            Descricao = "Camisa manga longa",
                            Observacao = "Desenvolvido para manter a temperatura corporal",
                            Preco = 415.00m,
                            Quantidade = 5,
                            Tamanho = "XXG"
                        });
                });

            modelBuilder.Entity("PedidoProduto", b =>
                {
                    b.Property<int>("PedidosId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutosId")
                        .HasColumnType("int");

                    b.HasKey("PedidosId", "ProdutosId");

                    b.HasIndex("ProdutosId");

                    b.ToTable("PedidoProduto");
                });

            modelBuilder.Entity("PedidoProduto", b =>
                {
                    b.HasOne("CoverAll_API.C_DAL.Model.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoverAll_API.C_DAL.Model.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
